use_frameworks!

target 'ByvStyles_Example' do
  pod 'ByvStyles', :path => '../'

  target 'ByvStyles_Tests' do
    inherit! :search_paths

    
  end
end

# # Workaround for Cocoapods issue #7606
# post_install do |installer|
#   installer.pods_project.build_configurations.each do |config|
#       config.build_settings.delete('CODE_SIGNING_ALLOWED')
#       config.build_settings.delete('CODE_SIGNING_REQUIRED')
#   end
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # add this line
    target.new_shell_script_build_phase.shell_script = "mkdir -p $PODS_CONFIGURATION_BUILD_DIR/#{target.name}"
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
  end
end
